### ISSUE TITLE
React + Craco Fails to Finish Simulation

### ISSUE THREAD

**Issue by josiahbryan** [memgraph/orb#102]
Any tricks to getting it running with React? I can run vanilla javascript examples on my machine if I clone the repo, but when I insert an example in to my react app -  Orb  never calls the orb.view.render callback!! (And nothing ever appears in my div/canvas)

![image](https://github.com/memgraph/orb/assets/4821548/782863ce-a693-44ab-a38f-a224c22862b6)

(Screenshot of console with debugging of the orb variable and the view itself - showing simulation started)

The react widget itself couldn't be simpler - using the example copied straight out of the Orb README for the actual Orb calls, and I just wrapped it in the necessary react calls to hook into the DOM:

```jsx
function CustomOrbGraphImpl() {
    const ref = useRef();

    useLayoutEffect(() => {
        const container = ref?.current;

        const orb = new Orb(container);
        const nodes = [
            { id: 1, label: 'Orb' },
            { id: 2, label: 'Graph' },
            { id: 3, label: 'Canvas' },
        ];
        const edges = [
            { id: 1, start: 1, end: 2, label: 'DRAWS' },
            { id: 2, start: 2, end: 3, label: 'ON' },
        ];

        // Initialize nodes and edges
        orb.data.setup({ nodes, edges });

        console.log(`Setting up graph on:`, {
            container,
            nodes,
            edges,
            orb,
            view: orb.view,
        });

        orb.view.render(() => {
            console.log(`View render done`);
            orb.view.recenter();
        });
    }, []);

    return <div className={'w-full h-full'} ref={ref} />;
}
```

I am using WebWorkers already in my React project AND I'm using craco to modify the webpack config without having to eject. I had to add the [contenthash] to get Orb to even load because React / craco didn't like more than one webworker in my project (I use webworkers for client-side AI inference already). I use the craco-worker-loader plugin to compile workers, config:

```js
{
    plugin: WorkerLoaderPlugin,
    options: {
        filename: '[path].[name].[contenthash].worker.js',
    },
},
```

(Had to add `[contenthash]` to the filename to get the workers to all load properly in my project - otherwise React failed to run the dev build with error: "Multiple assets emit different content to the same filename static/js/bundle.worker.js")

**Comment by antejavor** [comment]
Hi @josiahbryan, thanks for opening the issue 🚀 , someone will take over this and get back to you.

**Comment by AlexIchenskiy** [comment]
Hello @josiahbryan and thanks for your interest in Orb! We don't have a React adapter for orb, so I've been experimenting with craco to make it work. Here is the link to the [working minimal example](https://codesandbox.io/p/devbox/mkq7qd?migrateFrom=g6hfdj&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clvz7hx3o0006356jurv67wen%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clvz7hx3o0002356jy8sa1f3p%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clvz7hx3o0004356j17wp83g0%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clvz7hx3o0005356ja611xceg%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clvz7hx3o0002356jy8sa1f3p%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clvz7hx3n0001356j648k0wqc%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fpackage.json%2522%257D%255D%252C%2522id%2522%253A%2522clvz7hx3o0002356jy8sa1f3p%2522%252C%2522activeTabId%2522%253A%2522clvz7hx3n0001356j648k0wqc%2522%257D%252C%2522clvz7hx3o0005356ja611xceg%2522%253A%257B%2522id%2522%253A%2522clvz7hx3o0005356ja611xceg%2522%252C%2522activeTabId%2522%253A%2522clvz7skd0007r356jr091ls65%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522SETUP_TASKS%2522%252C%2522id%2522%253A%2522clvz7idii003t356jphup3nwm%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A3000%252C%2522id%2522%253A%2522clvz7skd0007r356jr091ls65%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522clvz7hx3o0004356j17wp83g0%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clvz7hx3o0003356jpx37rrey%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clvz7hxxb000pdhf86pq0642r%2522%257D%255D%252C%2522id%2522%253A%2522clvz7hx3o0004356j17wp83g0%2522%252C%2522activeTabId%2522%253A%2522clvz7hx3o0003356jpx37rrey%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D) of a React/Craco/Orb web application. I've managed to get it to work without using `craco-worker-loader` so I'd suggest using orb without it, if applicable. If not, please provide more details, ideally a minimal reproducible example, so I can reproduce the issue and help resolve it. I appreciate any additional info you can provide!

**Comment by josiahbryan** [comment]
Hi @AlexIchenskiy , no worries, thank you for taking the time to look into it - using `@craco/craco` instead of `craco-worker-loader` resolved it! My full `craco.config.js` is below in case anyone needs to see a working example - the only change I made to get it to work was switching the worker loader import to the one suggested, so thank you!

```js
const path = require('path');
const fs = require('fs');

// eslint-disable-next-line import/no-extraneous-dependencies
const CracoBabelLoader = require('craco-babel-loader');
// eslint-disable-next-line import/no-extraneous-dependencies
const CracoAlias = require('craco-alias');

// Automatically load and compile Web Workers
// const WorkerLoaderPlugin = require('craco-worker-loader');
// eslint-disable-next-line import/no-extraneous-dependencies
const WorkerLoaderPlugin = require('@craco/craco');

// manage relative paths to packages
const appDirectory = fs.realpathSync(process.cwd());
const resolvePackage = (relativePath) =>
	path.resolve(appDirectory, relativePath);

module.exports = {
	webpack: {
		headers: {
			'X-Frame-Options': 'Deny',
			'Cross-Origin-Embedder-Policy': 'require-corp',
			'Cross-Origin-Opener-Policy': 'same-origin',
		},
	},
	babel: {
		presets: [['@babel/preset-react', { runtime: 'automatic' }]],
		plugins: ['@babel/plugin-proposal-optional-chaining'],
	},
	plugins: [
		{
			plugin: CracoBabelLoader,
			options: {
				includes: [resolvePackage('node_modules/shared')],
			},
		},
		{
			plugin: CracoAlias,
			options: {
				source: 'options',
				baseUrl: './',
				aliases: {
					util: require.resolve('util/'),
					path: require.resolve('path-browserify'),
				},
			},
		},
		{
			plugin: WorkerLoaderPlugin,
			options: {
				filename: '[path].[name].[contenthash].worker.js',
			},
		},
	],
};
```
