### ISSUE TITLE
React template

### ISSUE THREAD

**Issue by alexanderbsd** [memgraph/orb#104]
Hi all,

Is there a simple template for React? Trying to integrate it using useRefs and orb.view.render doesn't seem to be called from useLayoutEffect. Thank you

**Comment by AlexIchenskiy** [comment]
Hello @alexanderbsd, thank you for your interest! You can find a working example [here](https://codesandbox.io/p/devbox/layout-semantic-maps-theme-forked-mkq7qd?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clvz7hx3o0006356jurv67wen%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clvz7hx3o0002356jy8sa1f3p%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clvz7hx3o0004356j17wp83g0%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clvz7hx3o0005356ja611xceg%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B60%252C40%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clvz7hx3o0002356jy8sa1f3p%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clvz7hx3n0001356j648k0wqc%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fpackage.json%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522cly4g7me6004m356l0uhtayjn%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A3%252C%2522startColumn%2522%253A37%252C%2522endLineNumber%2522%253A3%252C%2522endColumn%2522%253A37%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252Fcomponents%252FCustomOrbGraphImpl.jsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clvz7hx3o0002356jy8sa1f3p%2522%252C%2522activeTabId%2522%253A%2522cly4g7me6004m356l0uhtayjn%2522%257D%252C%2522clvz7hx3o0005356ja611xceg%2522%253A%257B%2522id%2522%253A%2522clvz7hx3o0005356ja611xceg%2522%252C%2522activeTabId%2522%253A%2522cly4gffco0032356jqta57lx0%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A3000%252C%2522id%2522%253A%2522cly4gffco0032356jqta57lx0%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522clvz7hx3o0004356j17wp83g0%2522%253A%257B%2522id%2522%253A%2522clvz7hx3o0004356j17wp83g0%2522%252C%2522activeTabId%2522%253A%2522cly4gdz2v001g356jsv3j9ruq%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cly4gdz2v001g356jsv3j9ruq%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522cly4gdyhm000sdihr09nf1i1k%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D). It uses `useLayoutEffect` along with `useRef` in the `CustomOrbGraphImpl` component to get it to work. If it does not seem useful, feel free to share your code so we can figure out how to make it work. I hope it helps!

**Comment by alexanderbsd** [comment]
Works well. Thanks a lot!

**Comment by AlexIchenskiy** [comment]
Glad I could help, feel free to ask if you have any further questions :)
