### ISSUE TITLE
Add canvas support for retina displays

### ISSUE THREAD

**Issue by tonilastre** [memgraph/orb#19]

**Comment by Fil** [comment]
thank you. It could be a parameter defaulting to devicePixelRatio, as in https://github.com/observablehq/stdlib/blob/main/src/dom/context2d.mjs#L2

**Comment by tonilastre** [comment]
A parameter (to the Orb's renderer) seems like a good option. Thanks for the link!

**Comment by tonilastre** [comment]
Will be released in v1.0.0.
