### ISSUE TITLE
Fix: Using Orb with Webpack4

### ISSUE THREAD

**Issue by KenCarroll** [memgraph/orb#28]
Exploring how to use Orb in a Vue/Nuxtjs project.  Get the following error:

ERROR in ./node_modules/@memgraph/orb/dist/simulator/types/web-worker-simulator/simulator.js 7:34
Module parse failed: Unexpected token (7:34)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|         this.worker = new Worker(new URL(
|         /* webpackChunkName: 'process.worker' */
>         './process.worker', import.meta.url));
|         this.worker.onmessage = ({ data }) => {
|             var _a, _b, _c, _d, _e, _f;

Researching the problem found this:

- https://substrate.stackexchange.com/questions/855/best-way-to-configure-webpack4-and-polkadot-dependencies-in-a-webworker

which led me to these:
- https://github.com/webpack/webpack/issues/6719
- https://www.npmjs.com/package/@open-wc/webpack-import-meta-loader
- npm i @open-wc/webpack-import-meta-loader

Adding loaders into nuxt.config.js https://nuxtjs.org/docs/features/configuration/#extend-webpack-config
  build: {
    extend(config, { isDev, isClient }) {
      // ..
      config.module.rules.push({
        test: /\.js$/,
        loader: require.resolve('@open-wc/webpack-import-meta-loader'),
      })
    }
  }

Now get this issue:
client.js?06a0:102 TypeError: _memgraph_orb__WEBPACK_IMPORTED_MODULE_0__.Orb.Orb is not a constructor

Questions:
1. Is this an issue or am I doing something wrong?
2. What's the right way to solve this?

Thanks,
Ken

**Comment by KenCarroll** [comment]
Hi @tonilastre created 'orbapp' to try to get orb working in a nuxtjs/vue project. But it wasn't the project where the above reported problem occurred. Was hoping to use 'orbapp' to try to replicate it...but have currently have a different problem (_memgraph_orb__WEBPACK_IMPORTED_MODULE_4__.Orb.Orb is not a constructor)

**Comment by colek42** [comment]
I am having the same issue with Parcel 2.7.0.

It looks for the source files and can not find them.  If I clone the src files into nod modules, I get the issue @KenCarroll is having

```
[web] 🚨 Build failed.
[web] [Error: ENOENT: no such file or directory, open '/src/node_modules/@memgraph/orb/src/simulator/types/web-worker-simulator/simulator.ts'] {
[web]   errno: -2,
[web]   code: 'ENOENT',
[web]   syscall: 'open',
[web]   path: '/src/node_modules/@memgraph/orb/src/simulator/types/web-worker-simulator/simulator.ts'
[web] }
[web] [Error: ENOENT: no such file or directory, open '/src/node_modules/@memgraph/orb/src/simulator/types/web-worker-simulator/simulator.ts'] {
[web]   errno: -2,
[web]   code: 'ENOENT',
[web]   syscall: 'open',
[web]   path: '/src/node_modules/@memgraph/orb/src/simulator/types/web-worker-simulator/simulator.ts'
[web] }
```

**Comment by tonilastre** [comment]
@KenCarroll and @colek42 - @jondlm has fixed the building of the `Orb` with Parcel! I think it should also work for a Vue/Nuxtjs project because of the same error message. You can check it out by downloading the latest orb version: [v0.1.5](https://www.npmjs.com/package/@memgraph/orb/v/0.1.5)

@jondlm once again thanks for the contribution! 🥇
