### ISSUE TITLE
MapView/DefaultView: resizeObserver not removed

### ISSUE THREAD

**Issue by markusnissl** [memgraph/orb#81]
I have seen that the ResizeObserver inside the views is not cleaned up properly.

In src/views/map-view.ts in the MapView class the following resizeObserver is created:

```
// Resize the canvas based on the dimensions of it's parent container <div>.
const resizeObs = new ResizeObserver(() => this._handleResize());
resizeObs.observe(this._container);
this._handleResize();
```

Similar in src/views/default-view.ts

In my opinion, a call to `resizeObs.unobserve()` is missing, when the `destroy()` method is called, and the observer has to put as a private class variable.

Currently, I receive following error after the graph instance has been destroyed:
```
leaflet-src.js:2456 Uncaught TypeError: Cannot read properties of undefined (reading '_leaflet_pos')
    at getPosition (leaflet-src.js:2456:14)
    at NewClass._getMapPanePos (leaflet-src.js:4455:12)
    at NewClass._rawPanBy (leaflet-src.js:4233:37)
    at NewClass.invalidateSize (leaflet-src.js:3548:12)
    at MapView._handleResize (map-view.js:304:27)
    at ResizeObserver.<anonymous> (map-view.js:42:57)
```

**Comment by markusnissl** [comment]
Hi @antejavor 

Yes opened a PR regarding this fix. 

Regarding your question:
We are working on a business application that visualises different companies on a map which we receive from Memgraph. Currently we only visualise nodes on the map, but working on edges as well.

**Comment by antejavor** [comment]
Cool @markusnissl, thanks a lot for your contribution, and keep us posted if anything else pops out! 🚀
